### ISSUE TITLE
Cmake error while compiling from the source 

### ISSUE THREAD

**Issue by BDehury85** [channotation/chap#14] opened 2019-09-10 09:44 UTC
CMakeFiles/googletest.dir/build.make:90: recipe for target 'googletest-prefix/src/googletest-stamp/googletest-download' failed
make[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1
CMakeFiles/Makefile2:429: recipe for target 'CMakeFiles/googletest.dir/all' failed
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Inniag** [comment] 2019-09-18 17:35
Closing this as duplicate of #15 .

**Closed** 2019-09-18 17:34 UTC
Labels: duplicate
